// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW6t6nL5vJawlB2hbtZUj3MDJMHLbbShg',
    appId: '1:899702442365:web:8ee32ab7be1ef4a9002414',
    messagingSenderId: '899702442365',
    projectId: 'teachspere-11e54',
    authDomain: 'teachspere-11e54.firebaseapp.com',
    storageBucket: 'teachspere-11e54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXmLr-xfbIkVJU9MuD7nBGshU5oW2KDg',
    appId: '1:899702442365:android:d702aa995da0731a002414',
    messagingSenderId: '899702442365',
    projectId: 'teachspere-11e54',
    storageBucket: 'teachspere-11e54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBinolctLuEGEXmb5Dftm4XaiafQIr4qtg',
    appId: '1:899702442365:ios:417b9193f80589f4002414',
    messagingSenderId: '899702442365',
    projectId: 'teachspere-11e54',
    storageBucket: 'teachspere-11e54.firebasestorage.app',
    iosBundleId: 'com.example.kabirAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBinolctLuEGEXmb5Dftm4XaiafQIr4qtg',
    appId: '1:899702442365:ios:417b9193f80589f4002414',
    messagingSenderId: '899702442365',
    projectId: 'teachspere-11e54',
    storageBucket: 'teachspere-11e54.firebasestorage.app',
    iosBundleId: 'com.example.kabirAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW6t6nL5vJawlB2hbtZUj3MDJMHLbbShg',
    appId: '1:899702442365:web:986bbda09ffe4827002414',
    messagingSenderId: '899702442365',
    projectId: 'teachspere-11e54',
    authDomain: 'teachspere-11e54.firebaseapp.com',
    storageBucket: 'teachspere-11e54.firebasestorage.app',
  );
}
